### ISSUE TITLE
Change the appearance of the GUI

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#1]
The GUI looks too dull at the moment.<be>
Make changes to the appearance of the GUI by changing the layout, size, colour scheme, etc.

**Comment by its-abhishek** [comment]
plss assign to me

**Comment by ghost** [comment]
assign is this to me #1 @charan2308

**Comment by charan2308** [comment]
@TharunK41 @its-abhishek  this issue is not open yet, waiting for all the other important features to be sorted out so that we can work on the appearance after that. Gimme few more hours and I will open it :)

**Comment by krishnapani** [comment]
can in please work on this 
Y L Krishna Pani
pes2ug21cs616

**Comment by Hiyanachnani** [comment]
can i get this issue assigned to me?
PES2202200178

**Comment by ad1tya24** [comment]
I would like to work on it

**Comment by tanishkapasarad** [comment]
hi can i work on this? PES2UG21CS570

**Comment by charan2308** [comment]
@Hiyanachnani  are you willing to work on this?

**Comment by charan2308** [comment]
@ad1tya24 @tanishkapasarad who's willing to work on this?

**Comment by arihan01** [comment]
Hi can I be assigned to this?

**Comment by Hiyanachnani** [comment]
> @Hiyanachnani are you willing to work on this?

yesss @charan2308

**Comment by ad1tya24** [comment]
I'm willing to work on this

**Comment by charan2308** [comment]
@Hiyanachnani work on this issue. Please update if you're working on it within 10 mins or I'll have to assign it to others in queue

**Comment by ghost** [comment]
> @TharunK41 @its-abhishek this issue is not open yet, waiting for all the other important features to be sorted out so that we can work on the appearance after that. Gimme few more hours and I will open it :)

now can I work on this @charan2308

**Comment by siddarthpai** [comment]
hey can i work on this

**Comment by siddarthpai** [comment]
please review pr
