### ISSUE TITLE
Add colour scheme

### ISSUE THREAD

**Issue by shrutidewan** [acmpesuecc/weatherforecast#13]
The GUI is really dull at the moment so make changes to the GUI by adding a new colour scheme.

**Comment by charan2308** [comment]
Go for it :) Make sure to use the latest version of the code.

**Comment by ghost** [comment]
can this be assigned to me @shrutidewan #13

**Comment by charan2308** [comment]
@TharunK41 , she raised the custom issue, so have to assign it to her,  text me on discord : Gowcha Daran#1340
