### ISSUE TITLE
New feature request: Display air quality parameters based on pincode

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#16]
Add a button called "pollution" which takes you to a different page where current air pollution data is displayed based on the Pincode entered by the user.
<b>NOTE: Use only the current air pollution data for this issue. And everything should be handled through the Tkinter GUI only</b>

Reference for the API <b>VERY IMPORTANT!</b> https://openweathermap.org/api/air-pollution

You will have 30 mins to work on this issue and report updates to the maintainer. If the maintainer is satisfied with your progress, time may be extended.

**Comment by siddarthpai** [comment]
can you assign this to me

**Comment by charan2308** [comment]
Go for it! Will check on it in 30 mins :)

**Comment by Ganther3301** [comment]
hey @charan2308  can i work on this pls?

**Comment by charan2308** [comment]
@Ganther3301 go ahead , need updates in 30 mins

**Comment by meghanagoru** [comment]
Hi, can I work on this?

**Comment by siddarthpai** [comment]
hey can i be reassigned

**Comment by Ganther3301** [comment]
> @Ganther3301 go ahead , need updates in 30 mins

okay so i've all my api requests ready. i just have to add it to the tkinter ui

**Comment by ad1tya24** [comment]
I would like to work on this

**Comment by charan2308** [comment]
@ad1tya24 I have already assigned this issue to someone who had requested earlier. Hence not able to assign the issue to you :(
