### ISSUE TITLE
Fixing Bug: Show results for Indian pincodes

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#19]
Right now, there's a strange bug. The results are being displayed only for USA pin codes and Indian pin codes are returning a 404 error.

**Comment by Ganther3301** [comment]
hey @charan2308  can you assign this to me

**Comment by charan2308** [comment]
@Ganther3301 go for it. Make sure that you update your code to the latest version before working on it.

**Comment by Ganther3301** [comment]
> @Ganther3301 go for it. Make sure that you update your code to the latest version before working on it.

yes it's done
