### ISSUE TITLE
Feature add: Display results on the GUI

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#2]
Currently, the results of the API are being displayed on the console. 
Ensure that the details are displayed on the GUI.

hints: use the Label method of Tkinter and update the values when the submit button is clicked.

**Comment by JawHawk** [comment]
Hey I can work on this issue, pls assign me.

**Comment by shrutidewan** [comment]
Can you assign me to this?

**Comment by tanishkapasarad** [comment]
can i work on this? tanishka pasarad

**Comment by surajkadapa** [comment]
Can I please be assigned to this? Suraj

**Comment by VishalCE7** [comment]
Could you please assign me this issue
Vishal C E
PES2UG20CS386

**Comment by MotoMoto418** [comment]
Hi! I'd like to be assigned to this issue
SRN: PES2UG21CS479
@charan2308

**Comment by ad1tya24** [comment]
I would like to work on it
