### ISSUE TITLE
Changing the format of temperature and humidity.

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#3]
The temperature is displayed on the console in Kelvin format, and the humidity is displayed as a percentage.
Modify the code such that temperature is displayed in degree celsius and humidity is displayed as a decimal value(eg:20 per cent should be displayed as .20)

**Comment by sssai44** [comment]
Hey can I get this issue assigned... R S Shanmukha Sai PES2202200609

**Comment by sukruthi-s** [comment]
please assign this issue (sukruthi sanampudi PES2UG21CS472)

**Comment by Tree1527** [comment]
Could I get this issue assigned to me
Aditya Rajendra Shinde
PES2202200479

**Comment by VishalCE7** [comment]
Could you please assign me to this issue
Vishal C E
PES2UG20CS386

**Comment by MotoMoto418** [comment]
Hi! I'd like to get assigned to this issue 
SRN: PES2UG21CS479

**Comment by tanishkapasarad** [comment]
hey can i be assigned this issue?
PES2UG21CS570

**Comment by kashish0604** [comment]
hey can you assign this issue to me i caan work on it

**Comment by ghost** [comment]
can this be assigned to me @charan2308
