### ISSUE TITLE
Change colour Button issue

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#35]
Whenever you click on the change colour button , there's a error on the console popping up .

**Comment by uditagrawal08** [comment]
@charan2308 I want to work on this issue please explain

**Comment by kabir325** [comment]
hello i want to work on the issue

**Comment by avdhagam** [comment]
I want to be assigned to this

**Comment by anshiiJ** [comment]
i want to work on this pls assign and expain

**Comment by BhavikaPradeep** [comment]
i want to fix this issue

**Comment by entity012** [comment]
i want to be assigned to this

**Comment by ManushriJ** [comment]
can i be assigned'

**Comment by RitwikAg120** [comment]
i want to fix this issue

**Comment by parvashah305** [comment]
i want to fix this issue

**Comment by dexPagma** [comment]
can i be assigned this issue? @charan2308

**Comment by SafwanAhmed08** [comment]
can i get this issue

**Comment by skandesh-kk** [comment]
I wish to work on this ,assign this to me

**Comment by sid-nc** [comment]
can i get assigned

**Comment by pratham-exe** [comment]
can i be assigned for this issue

**Comment by 7Akshu77** [comment]
can i get assigned for this issue

**Comment by kavs2803** [comment]
could i be assigned with this issue please?

**Comment by SafwanAhmed08** [comment]
Can i get assigned for this now?

**Comment by M-SriVidya** [comment]
can I please get assigned to fix this issue? I've figured the code to fix it

**Comment by RisuKumari11** [comment]
can I get this issue

**Comment by 1anagha7** [comment]
can i get assigned to this?

**Comment by faizanpas** [comment]
can i be assigned to this?

**Comment by SafwanAhmed08** [comment]
@charan2308 can i get assigned to this

**Comment by ShankyTaco** [comment]
Please assign me this issue

**Comment by GauthamdevRHolla** [comment]
Can I get assigned to this

**Comment by komulannister** [comment]
can i get assigned to this please?

**Comment by ProSai45** [comment]
Hey Can You Assign Me This Issue

**Comment by devanshishukla17** [comment]
can i be assigned this issue

**Comment by DedLad** [comment]
welp i have the fix already just givme this

**Comment by Keeru-2005** [comment]
i want to work on this, hope u understand

**Comment by likhitharigela** [comment]
Can i get assigned to you pls

**Comment by HackerGlory** [comment]
please assign this to me

**Comment by anshiiJ** [comment]
can i get assigned to this pls?

**Comment by saivihitha17** [comment]
i wanna fix it

**Comment by neethanm** [comment]
can i get assigned to #35
