### ISSUE TITLE
App crashing on clicking the next page button twice

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#38]
There's a bug in the application. This bug can be recreated by following these steps:

1. While on the main page, click on next page option.
2. Now click on previous page option and the main page reappears
3. Now on clicking the next page button, the app crashes

**Comment by NishanHolla** [comment]
can i be assiged ?

**Comment by siri-n-shetty** [comment]
COuld you please please assign this to me?

**Comment by sxijyoti** [comment]
can i be assigned this?

**Comment by swayamchhaba** [comment]
can i be assigned?

**Comment by NJWasTaken** [comment]
Can I be assigned?

**Comment by charan2308** [comment]
@NishanHolla go ahead with it

**Comment by NishanHolla** [comment]
Got another task please assign to someonne else .

**Comment by charan2308** [comment]
if anyone wants to work on this please request
