### ISSUE TITLE
Display the units along with the values on the GUI

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#8]
At the moment, only the numerical values of temperature, and pressure are being displayed. Make changes such that the units are mentioned along with the numerical values.

**Comment by nik2203** [comment]
hi can i be assigned to this
PES2UG21CS334
Nikhil Girish

**Comment by charan2308** [comment]
@nik2203 go for it , revert back within 15 mins

**Comment by vrac10** [comment]
hi , can i be assigned to this 
PES2202200278
Rachit verma

**Comment by nik2203** [comment]
> @nik2203 go for it , revert back within 15 mins

im almost done, gonna submit pr in a min

**Comment by charan2308** [comment]
@vrac10 I have already assigned this issue to someone who had requested earlier. Hence not able to assign the issue to you :(

**Comment by charan2308** [comment]
@nik2203 cool, waiting for it

**Comment by nik2203** [comment]
> @nik2203 cool, waiting for it 

submitted 👍🏽 thank you so much for waiting

**Comment by charan2308** [comment]
@nik2203 good job, but also make sure that the units are displayed on the GUI also. Hint: concatenate the unit to the value while changing the text of the label in the fetch() function. Giving you 10-15 mins for this.

**Comment by nik2203** [comment]
> @nik2203 good job, but also make sure that the units are displayed on the GUI also. Hint: concatenate the unit to the value while changing the text of the label in the fetch() function. Giving you 10-15 mins for this.  

got it. im currently unable to create an account on the website mentioned in the readme though. what should i do?

**Comment by nik2203** [comment]
> @nik2203 good job, but also make sure that the units are displayed on the GUI also. Hint: concatenate the unit to the value while changing the text of the label in the fetch() function. Giving you 10-15 mins for this.  

updated 👍🏽. units now appear on gui and concatenation fixed

**Comment by charan2308** [comment]
@nik2203 good job, have assigned 5 bounty points and 5 brownie points for extra effort :)
