### ISSUE TITLE
Typo correction and punctuation

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/weatherforecast#9]
The fields that are being displayed on the GUI are not punctuated properly. Make sure all the fields (such as temperature, pressure, etc..) are capitalised properly and replace '=' (equals to)signs with ':' (colon).

**Comment by Tree1527** [comment]
Could I have this issue assigned to me
Aditya Rajendra Shinde
PES2202200479

**Comment by charan2308** [comment]
@Tree1527 pls revert back in 15 mins. Go for it :)
